<a href="https://colab.research.google.com/github/jamesohara155/first-repo/blob/main/OHara_20261007.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
salaries = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vQ35pd42Mm0jJlRaA5BTmfOBAVzDHilEoh055xvEjDUmF0q2vbH2ttjda5I_1Q6rw/pub?output=csv") ##create data frame from UNC salaries

In [ ]:
salaries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14568 entries, 0 to 14567
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   INSTITUTION NAME             14568 non-null  object
 1   LAST NAME                    14568 non-null  object
 2   FIRST NAME                   14568 non-null  object
 3   INIT                         14421 non-null  object
 4   AGE                          14568 non-null  int64
 5   INITIAL HIRE DATE            14568 non-null  object
 6   JOB CATEGORY                 14568 non-null  object
 7   EMPLOYEE ANNUAL BASE SALARY  14568 non-null  float64
 8   EMPLOYEE HOME DEPARTMENT     14568 non-null  object
 9   PRIMARY WORKING TITLE        14568 non-null  object
dtypes: float64(1), int64(1), object(8)
memory usage: 1.1+ MB

In [ ]:
unc_salaries = salaries[salaries['INSTITUTION NAME'] == 'UNC-CH']##unc dataframe

In [ ]:
uncsa_salaries = salaries[salaries['INSTITUTION NAME'] == 'UNCSA'] ##uncsa dataframe

In [ ]:
unc_salaries['EMPLOYEE ANNUAL BASE SALARY'].mean() ##average salary at unc

np.float64(114511.21662549688)

In [ ]:
uncsa_salaries['EMPLOYEE ANNUAL BASE SALARY'].mean() ##average salary at uncsa

np.float64(72822.5366875)

In [ ]:
salaries.groupby('INSTITUTION NAME')['EMPLOYEE ANNUAL BASE SALARY'].mean() ##average salary of both institutions in same dataframe

INSTITUTION NAME
UNC-CH    114511.216625
UNCSA      72822.536688
Name: EMPLOYEE ANNUAL BASE SALARY, dtype: float64

In [ ]:
##bins should be equal sizes, round numbers, bins also come from realistic reasons

In [ ]:
bins_we_made = [0,100000,200000,300000,400000,500000,600000,700000,800000,900000,1000000, float('inf')] ## create bins, float('inf') means setting last bin limit at infinity

In [ ]:
pd.cut(salaries['EMPLOYEE ANNUAL BASE SALARY'],
       bins=bins_we_made,
       right=False).value_counts().sort_index().to_frame() #apply bins to salaries, count how many people in each bin, sort groups in size order, apply to dataframe

                             count
EMPLOYEE ANNUAL BASE SALARY
[0.0, 100000.0)               9038
[100000.0, 200000.0)          3685
[200000.0, 300000.0)          1226
[300000.0, 400000.0)           394
[400000.0, 500000.0)           149
[500000.0, 600000.0)            35
[600000.0, 700000.0)            26
[700000.0, 800000.0)             4
[800000.0, 900000.0)             4
[900000.0, 1000000.0)            2
[1000000.0, inf)                 5

working with dates

In [ ]:
salaries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14568 entries, 0 to 14567
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   INSTITUTION NAME             14568 non-null  object
 1   LAST NAME                    14568 non-null  object
 2   FIRST NAME                   14568 non-null  object
 3   INIT                         14421 non-null  object
 4   AGE                          14568 non-null  int64
 5   INITIAL HIRE DATE            14568 non-null  object
 6   JOB CATEGORY                 14568 non-null  object
 7   EMPLOYEE ANNUAL BASE SALARY  14568 non-null  float64
 8   EMPLOYEE HOME DEPARTMENT     14568 non-null  object
 9   PRIMARY WORKING TITLE        14568 non-null  object
dtypes: float64(1), int64(1), object(8)
memory usage: 1.1+ MB

In [ ]:
salaries['INITIAL HIRE DATE'] = pd.to_datetime(salaries['INITIAL HIRE DATE']) ##convert dates to numbers

/tmp/ipykernel_1102/3222072828.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  salaries['INITIAL HIRE DATE'] = pd.to_datetime(salaries['INITIAL HIRE DATE']) ##convert dates to numbers

In [ ]:
salaries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14568 entries, 0 to 14567
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   INSTITUTION NAME             14568 non-null  object
 1   LAST NAME                    14568 non-null  object
 2   FIRST NAME                   14568 non-null  object
 3   INIT                         14421 non-null  object
 4   AGE                          14568 non-null  int64
 5   INITIAL HIRE DATE            14568 non-null  datetime64[ns]
 6   JOB CATEGORY                 14568 non-null  object
 7   EMPLOYEE ANNUAL BASE SALARY  14568 non-null  float64
 8   EMPLOYEE HOME DEPARTMENT     14568 non-null  object
 9   PRIMARY WORKING TITLE        14568 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(1), object(7)
memory usage: 1.1+ MB

In [ ]:
salaries.head()

,INSTITUTION NAME,LAST NAME,FIRST NAME,INIT,AGE,INITIAL HIRE DATE,JOB CATEGORY,EMPLOYEE ANNUAL BASE SALARY,EMPLOYEE HOME DEPARTMENT,PRIMARY WORKING TITLE
0,UNC-CH,ABAD FERNANDEZ,MARIA,,41,2014-02-01,Assistant Professor,96873.0,Microbiology and Immunology,Research Assistant Professor
1,UNC-CH,ABAJAS,YASMINA,L,43,2012-07-01,Associate Professor,199000.0,Peds-Hematology/Oncology,Clinical Associate Professor
2,UNC-CH,ABBENANTE,DOMINIC,A,43,2014-06-16,IT Technical Support/Paraprofessional,70319.0,Kenan-Flagler Bus Sch,Technology Support Analyst
3,UNC-CH,ABELS,KIMBERLY,T,63,1995-08-01,"Assoc/Asst Dean, Undergraduate Programs",145000.0,Center for Student Success,Associate Dean
4,UNC-CH,ABRAMOWITZ,JONATHAN,S,57,2006-07-01,Professor,157476.0,Psychology and Neuroscience,Professor

In [ ]:
pd.to_numeric(salaries['INITIAL HIRE DATE']) ##check hire date

0        1391212800000000000
1        1341100800000000000
2        1402876800000000000
3         807235200000000000
4        1151712000000000000
                ...
14563    1262304000000000000
14564    1480550400000000000
14565    1488326400000000000
14566    1407801600000000000
14567    1515456000000000000
Name: INITIAL HIRE DATE, Length: 14568, dtype: int64

In [ ]:
salaries['INITIAL HIRE DATE'].dt.year ##check which year hired

0        2014
1        2012
2        2014
3        1995
4        2006
         ...
14563    2010
14564    2016
14565    2017
14566    2014
14567    2018
Name: INITIAL HIRE DATE, Length: 14568, dtype: int32

In [ ]:
pd.Timestamp.today() ##timestamp of now

Timestamp('2026-10-14 14:14:21.248081')

In [ ]:
pd.Timestamp.today().year ##timestamp of now in years

2026

In [ ]:
salaries['years_worked'] = pd.Timestamp.today().year - salaries['INITIAL HIRE DATE'].dt.year ##about how many years have they worked here

In [ ]:
salaries

,INSTITUTION NAME,LAST NAME,FIRST NAME,INIT,AGE,INITIAL HIRE DATE,JOB CATEGORY,EMPLOYEE ANNUAL BASE SALARY,EMPLOYEE HOME DEPARTMENT,PRIMARY WORKING TITLE,years_worked
0,UNC-CH,ABAD FERNANDEZ,MARIA,,41,2014-02-01,Assistant Professor,96873.0,Microbiology and Immunology,Research Assistant Professor,12
1,UNC-CH,ABAJAS,YASMINA,L,43,2012-07-01,Associate Professor,199000.0,Peds-Hematology/Oncology,Clinical Associate Professor,14
2,UNC-CH,ABBENANTE,DOMINIC,A,43,2014-06-16,IT Technical Support/Paraprofessional,70319.0,Kenan-Flagler Bus Sch,Technology Support Analyst,12
3,UNC-CH,ABELS,KIMBERLY,T,63,1995-08-01,"Assoc/Asst Dean, Undergraduate Programs",145000.0,Center for Student Success,Associate Dean,31
4,UNC-CH,ABRAMOWITZ,JONATHAN,S,57,2006-07-01,Professor,157476.0,Psychology and Neuroscience,Professor,20
...,...,...,...,...,...,...,...,...,...,...,...
14563,UNCSA,Yokeley,Allison,R,49,2010-01-01,Faculty (High School and Elementary),72243.0,High School Academic Programs,High School Instructor,16
14564,UNCSA,Young,Timothy,E,44,2016-12-01,Corporate / Foundation Relations Professional,70707.0,Advancement,University Program Specialist,10
14565,UNCSA,Zayas,Nicholas,NaN,38,2017-03-01,Administrative Assistant,39011.0,Admissions,Administrative Support Assoc,9
14566,UNCSA,Zerbe,Jennet,NaN,63,2014-08-12,Professor,99139.0,School of Dance,Professor,12
14567,UNCSA,Zubick,Kimberly,R,64,2018-01-09,Assistant Professor,71200.0,School of Filmmaking,Assistant Professor,8

In [ ]:
##homework is to create new column called age hired

In [ ]:
salaries['age_hired'] = salaries['AGE'] - salaries['years_worked']

In [ ]:
salaries

,INSTITUTION NAME,LAST NAME,FIRST NAME,INIT,AGE,INITIAL HIRE DATE,JOB CATEGORY,EMPLOYEE ANNUAL BASE SALARY,EMPLOYEE HOME DEPARTMENT,PRIMARY WORKING TITLE,years_worked,age_hired
0,UNC-CH,ABAD FERNANDEZ,MARIA,,41,2014-02-01,Assistant Professor,96873.0,Microbiology and Immunology,Research Assistant Professor,12,29
1,UNC-CH,ABAJAS,YASMINA,L,43,2012-07-01,Associate Professor,199000.0,Peds-Hematology/Oncology,Clinical Associate Professor,14,29
2,UNC-CH,ABBENANTE,DOMINIC,A,43,2014-06-16,IT Technical Support/Paraprofessional,70319.0,Kenan-Flagler Bus Sch,Technology Support Analyst,12,31
3,UNC-CH,ABELS,KIMBERLY,T,63,1995-08-01,"Assoc/Asst Dean, Undergraduate Programs",145000.0,Center for Student Success,Associate Dean,31,32
4,UNC-CH,ABRAMOWITZ,JONATHAN,S,57,2006-07-01,Professor,157476.0,Psychology and Neuroscience,Professor,20,37
...,...,...,...,...,...,...,...,...,...,...,...,...
14563,UNCSA,Yokeley,Allison,R,49,2010-01-01,Faculty (High School and Elementary),72243.0,High School Academic Programs,High School Instructor,16,33
14564,UNCSA,Young,Timothy,E,44,2016-12-01,Corporate / Foundation Relations Professional,70707.0,Advancement,University Program Specialist,10,34
14565,UNCSA,Zayas,Nicholas,NaN,38,2017-03-01,Administrative Assistant,39011.0,Admissions,Administrative Support Assoc,9,29
14566,UNCSA,Zerbe,Jennet,NaN,63,2014-08-12,Professor,99139.0,School of Dance,Professor,12,51
14567,UNCSA,Zubick,Kimberly,R,64,2018-01-09,Assistant Professor,71200.0,School of Filmmaking,Assistant Professor,8,56

In [ ]:
salaries[(salaries['EMPLOYEE ANNUAL BASE SALARY'] >= 900000) & (salaries['EMPLOYEE ANNUAL BASE SALARY'] <= 1000000)]

,INSTITUTION NAME,LAST NAME,FIRST NAME,INIT,AGE,INITIAL HIRE DATE,JOB CATEGORY,EMPLOYEE ANNUAL BASE SALARY,EMPLOYEE HOME DEPARTMENT,PRIMARY WORKING TITLE,years_worked,age_hired
1031,UNC-CH,Belichick,William,,74,2024-12-16,Head Coach - Football,1000000.0,Ath Football Office,Coach,2,72
1887,UNC-CH,CUNNINGHAM,LAWRENCE,R,64,2011-11-14,Chief Athletics Administrator,903438.0,Ath Administration,Athletic Director,15,49
9847,UNC-CH,Petrino,Robert,P,65,2026-01-06,Assistant Coach - Football,1000000.0,Ath Football Office,Assistant Coach,0,65
12288,UNC-CH,Tanner,James,L,57,2025-03-17,"Athletics, General Manager, Basketball",950000.0,Ath Men's Basketball,Administrative Coordinator,1,56

In [ ]:
salaries[salaries['EMPLOYEE ANNUAL BASE SALARY'].between(900000, 10000000)]

,INSTITUTION NAME,LAST NAME,FIRST NAME,INIT,AGE,INITIAL HIRE DATE,JOB CATEGORY,EMPLOYEE ANNUAL BASE SALARY,EMPLOYEE HOME DEPARTMENT,PRIMARY WORKING TITLE,years_worked,age_hired
1030,UNC-CH,Belichick,Stephen,C,39,2025-01-07,Assistant Coach - Football,1400000.0,Ath Football Office,Assistant Coach,1,38
1031,UNC-CH,Belichick,William,,74,2024-12-16,Head Coach - Football,1000000.0,Ath Football Office,Coach,2,72
1887,UNC-CH,CUNNINGHAM,LAWRENCE,R,64,2011-11-14,Chief Athletics Administrator,903438.0,Ath Administration,Athletic Director,15,49
7494,UNC-CH,Lombardi,Michael,R,67,2024-12-14,"Academic Services Professional, Asst/Assoc Ath...",1500000.0,Ath Football Office,Administrative Coordinator,2,65
7967,UNC-CH,Malone,Michael,,57,2026-04-07,Head Coach - Men's Basketball,7500000.0,Ath Men's Basketball,Coach,0,57
9847,UNC-CH,Petrino,Robert,P,65,2026-01-06,Assistant Coach - Football,1000000.0,Ath Football Office,Assistant Coach,0,65
12288,UNC-CH,Tanner,James,L,57,2025-03-17,"Athletics, General Manager, Basketball",950000.0,Ath Men's Basketball,Administrative Coordinator,1,56

In [ ]:
salaries['JOB CATEGORY RECODED'] = salaries['JOB CATEGORY'].case_when(
  [
    (salaries['JOB CATEGORY'].str.contains(
      'coach', case=False, na=False),
    'Coach'

    )
,

    (salaries['JOB CATEGORY'].str.contains(
      'professor', case=False, na=False),
    'Professor'

   )
  ]
)

In [ ]:
salaries

,INSTITUTION NAME,LAST NAME,FIRST NAME,INIT,AGE,INITIAL HIRE DATE,JOB CATEGORY,EMPLOYEE ANNUAL BASE SALARY,EMPLOYEE HOME DEPARTMENT,PRIMARY WORKING TITLE,years_worked,age_hired,JOB CATEGORY RECODED
0,UNC-CH,ABAD FERNANDEZ,MARIA,,41,2014-02-01,Assistant Professor,96873.0,Microbiology and Immunology,Research Assistant Professor,12,29,Professor
1,UNC-CH,ABAJAS,YASMINA,L,43,2012-07-01,Associate Professor,199000.0,Peds-Hematology/Oncology,Clinical Associate Professor,14,29,Professor
2,UNC-CH,ABBENANTE,DOMINIC,A,43,2014-06-16,IT Technical Support/Paraprofessional,70319.0,Kenan-Flagler Bus Sch,Technology Support Analyst,12,31,IT Technical Support/Paraprofessional
3,UNC-CH,ABELS,KIMBERLY,T,63,1995-08-01,"Assoc/Asst Dean, Undergraduate Programs",145000.0,Center for Student Success,Associate Dean,31,32,"Assoc/Asst Dean, Undergraduate Programs"
4,UNC-CH,ABRAMOWITZ,JONATHAN,S,57,2006-07-01,Professor,157476.0,Psychology and Neuroscience,Professor,20,37,Professor
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14563,UNCSA,Yokeley,Allison,R,49,2010-01-01,Faculty (High School and Elementary),72243.0,High School Academic Programs,High School Instructor,16,33,Faculty (High School and Elementary)
14564,UNCSA,Young,Timothy,E,44,2016-12-01,Corporate / Foundation Relations Professional,70707.0,Advancement,University Program Specialist,10,34,Corporate / Foundation Relations Professional
14565,UNCSA,Zayas,Nicholas,NaN,38,2017-03-01,Administrative Assistant,39011.0,Admissions,Administrative Support Assoc,9,29,Administrative Assistant
14566,UNCSA,Zerbe,Jennet,NaN,63,2014-08-12,Professor,99139.0,School of Dance,Professor,12,51,Professor
14567,UNCSA,Zubick,Kimberly,R,64,2018-01-09,Assistant Professor,71200.0,School of Filmmaking,Assistant Professor,8,56,Professor

In [ ]:
salaries['JOB CATEGORY RECODED B'] = salaries['JOB CATEGORY'].case_when(
  [(salaries['JOB CATEGORY'].isin(['Administrative Assistant', "IT Support", 'Facilities']),
   'Back Office'
  )
]
  )

In [ ]:
salaries

,INSTITUTION NAME,LAST NAME,FIRST NAME,INIT,AGE,INITIAL HIRE DATE,JOB CATEGORY,EMPLOYEE ANNUAL BASE SALARY,EMPLOYEE HOME DEPARTMENT,PRIMARY WORKING TITLE,years_worked,age_hired,JOB CATEGORY RECODED,JOB CATEGORY RECODED B
0,UNC-CH,ABAD FERNANDEZ,MARIA,,41,2014-02-01,Assistant Professor,96873.0,Microbiology and Immunology,Research Assistant Professor,12,29,Professor,Assistant Professor
1,UNC-CH,ABAJAS,YASMINA,L,43,2012-07-01,Associate Professor,199000.0,Peds-Hematology/Oncology,Clinical Associate Professor,14,29,Professor,Associate Professor
2,UNC-CH,ABBENANTE,DOMINIC,A,43,2014-06-16,IT Technical Support/Paraprofessional,70319.0,Kenan-Flagler Bus Sch,Technology Support Analyst,12,31,IT Technical Support/Paraprofessional,IT Technical Support/Paraprofessional
3,UNC-CH,ABELS,KIMBERLY,T,63,1995-08-01,"Assoc/Asst Dean, Undergraduate Programs",145000.0,Center for Student Success,Associate Dean,31,32,"Assoc/Asst Dean, Undergraduate Programs","Assoc/Asst Dean, Undergraduate Programs"
4,UNC-CH,ABRAMOWITZ,JONATHAN,S,57,2006-07-01,Professor,157476.0,Psychology and Neuroscience,Professor,20,37,Professor,Professor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14563,UNCSA,Yokeley,Allison,R,49,2010-01-01,Faculty (High School and Elementary),72243.0,High School Academic Programs,High School Instructor,16,33,Faculty (High School and Elementary),Faculty (High School and Elementary)
14564,UNCSA,Young,Timothy,E,44,2016-12-01,Corporate / Foundation Relations Professional,70707.0,Advancement,University Program Specialist,10,34,Corporate / Foundation Relations Professional,Corporate / Foundation Relations Professional
14565,UNCSA,Zayas,Nicholas,NaN,38,2017-03-01,Administrative Assistant,39011.0,Admissions,Administrative Support Assoc,9,29,Administrative Assistant,Back Office
14566,UNCSA,Zerbe,Jennet,NaN,63,2014-08-12,Professor,99139.0,School of Dance,Professor,12,51,Professor,Professor
14567,UNCSA,Zubick,Kimberly,R,64,2018-01-09,Assistant Professor,71200.0,School of Filmmaking,Assistant Professor,8,56,Professor,Assistant Professor